name: Link Check

on:
  schedule:
    - cron: '0 0 1 * *' # Run monthly
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --accept=200,204,429 --exclude-loopback --no-progress './**/*.md'
